In [0]:
import scipy.signal
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_mldata
import time
from IPython import display

In [0]:
# grayscale and inline plotting
%matplotlib inline
plt.rcParams['image.cmap'] = 'gray'

In [0]:
# using scipy's 2d convolution function
conv = scipy.signal.convolve# modes include "full", "valid", and "same"
conv2 = scipy.signal.convolve2d # modes include "full", "valid", and "same"

In [4]:
w = [1, 2, 3]
s = [0, 1, 0.5]

np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

### Exercise 1. Complete the following code to implement 1D "full" convolution. You need only fill in the question marks.

In [0]:
"""
`CONV_FULL` - 1D "full" convolution

    R = CONV_FULL(W, S) 

* `W`: 1D array
* `S`: 1D array
* `R`: "full" convolution of W and S
"""
def conv_full(w,s):
    r = np.zeros(len(w)+len(s)-1)
    for i in range(len(w)):
        for j in range(len(s)):
            r[i+j] += w[i]*s[j]
    return r

### Test your function by comparing with the built-in `conv` function. The output of the following should be true, if your code is correct.

In [9]:
a = np.random.rand(10)
b = np.random.rand(3)
np.isclose(conv_full(a,b), conv(a,b)).all()

True

### Exercise 2. Complete the following code to implement 2D "full" convolution. You need only fill in the question marks.

In [0]:
"""
`CONV2_FULL` - 2D "full" convolution

    R = CONV2_FULL(W, S) 

* `W`: 2D array
* `S`: 2D array
* `R`: "full" convolution of W and S
"""
def conv2_full(w,s):
    wsize1, wsize2 = w.shape
    ssize1, ssize2 = s.shape
    r = np.zeros([wsize1+ssize1-1, wsize2+ssize2-1])
    for i1 in range(wsize1):
        for i2 in range(wsize2):
            for j1 in range(ssize1):
                for j2 in range(ssize2):
                    r[i1+j1, i2+j2] += w[i1, i2] * s[j1, j2]
    return r

### Test your function by comparing with the built-in `conv2` function. The output of the following should be true, if your code is correct.

In [11]:
a = np.random.rand(10,6)
b = np.random.rand(3,2)
np.isclose(conv2_full(a,b), conv2(a,b)).all()

True

### Exercise 3. In class you learned that 1D convolution is equivalent to multiplication by a Toeplitz matrix, where the size of the matrix depends on the length of the input signal. Complete the following code to construct the matrix. You need only fill in the question marks.

In [0]:
"""
`CONVMTX` - 1D convolution matrix

    MTX = CONVMTX(KERNEL, INSIZE) 

* `KERNEL`: kernel of the convolution
* `INSIZE`: length of the input signal
* `MTX`: multiplication by MTX is equivalent to convolution by KERNEL
"""
def convmtx(kernel, insize, shape = "full"):
    kernelsize = len(kernel)
    outsize = kernelsize + insize - 1 
    mtx = np.zeros([outsize, insize])

    for i in range(insize):
        mtx[i:i+kernelsize, i] = kernel

    if shape == "valid":
        mtx = mtx[kernelsize-1 : insize , :]
    
    return mtx

### Test that multiplication by your matrix is equivalent to convolution. The output of the following should be true, if your code is correct.

In [16]:
kernel = np.random.rand(3)
sig = np.random.rand(7)
np.isclose(np.dot(convmtx(kernel,len(sig),"full"), sig), conv(kernel,sig,"full")).any()

True

In [17]:
np.isclose(np.dot(convmtx(kernel,len(sig),"valid"), sig), conv(kernel,sig,"valid")).any()

True

### The following illustrates that the transpose of a convolution matrix is equal to a convolution matrix with a flipped kernel. 

In [0]:
kernel = np.array([1,2,3])

In [19]:
convmtx(kernel,5,"valid")

array([[3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.]])

In [20]:
convmtx(kernel[::-1],3, "full")     # the kernel is flipped

array([[3., 0., 0.],
       [2., 3., 0.],
       [1., 2., 3.],
       [0., 1., 2.],
       [0., 0., 1.]])

There's no coding to do here. Just verify for yourself that the above two matrices are transposes of each other.  Note that transpose changes valid to full, and vice versa. This is why the backward pass for a convolutional net contains flipped kernels. These are equivalent to the transposed matrices in the backward pass for a neural net.