**Design a ConvNet that detects the fixed pattern anywhere in a binary 9x9 input image**

In [0]:
import numpy as np
import scipy
from scipy import signal
conv2d = scipy.signal.convolve2d  # np.convolve only supports 1-d array 

In [0]:
image = np.array([
[1, 1, 1, 1, 0, 0, 0, 0, 0],
[1, 0, 0, 1, 0, 0, 0, 0, 0],
[1, 0, 0, 1, 0, 0, 0, 1, 1],
[1, 1, 1, 1, 0, 0, 1, 1, 0],
[0, 0, 0, 0, 0, 1, 0, 1, 0],
[0, 0, 0, 0, 0, 1, 1, 1, 1],
[0, 0, 0, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 0, 0, 1, 0, 0, 1],
[0, 0, 0, 0, 0, 1, 1, 1, 1],
])

image_large = np.array([
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0],
[1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0],
[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
])

In [3]:
image.shape

(9, 9)

In [0]:
def detect(figure):
  print 'Detection started!'
  print 'input fig: \n', figure
  print '\n'
  
  kernel_1_1 = np.array([
    [ 1, 1, 1], 
    [ 1,-1,-1],
    [ 1,-1,-1],
    ])
  # kernel_1_1 is for detection of pattern in the input image: 
  #  [ 0, 0, 1], 
  #  [ 0, 0, 1],
  #  [ 1, 1, 1],
 
  
  kernel_1_2 = np.array([
    [ 1, 1, 1], 
    [-1,-1, 1],
    [-1,-1, 1],
    ])
  
  kernel_1_3 = np.array([
    [ 1,-1,-1], 
    [ 1,-1,-1],
    [ 1, 1, 1],
    ])
 
  kernel_1_4 = np.array([
    [-1,-1, 1], 
    [-1,-1, 1],
    [ 1, 1, 1],
    ])
  
  kernel_1s = [kernel_1_1, kernel_1_2, kernel_1_3, kernel_1_4]  # kernels for detecting four corners in the fixed pattern 
  sum_output_l1 = np.zeros(conv2d(figure,kernel_1_1,'valid').shape) 
  
  for i in range(len(kernel_1s)):
    sum_output_l1 += np.where(conv2d(figure,kernel_1s[i],'valid') >= 5, 1, 0)  # for each kernel in kernel_1s, the threshold is 5 
  
  final_output_l1 = sum_output_l1
  
  # print the first layer output
  print 'first layer final output: \n', sum_output_l1
  print '\n'
  
  
  kernel_2 = np.array([
    [ 1, 1],
    [ 1, 1]
    ])
  # kernel_2 is for detection of pattern: 
  #  [ 1, 1], 
  #  [ 1, 1], in the final_output_l1
  
  output_l2 = conv2d(final_output_l1,kernel_2,'valid')
  
  final_output_l2 = np.where(output_l2 >= 4, 1, 0) # for kernel_2, the threshold is also 4 
  
  # print the final layer (second layer) output
  print 'final detection: \n', final_output_l2
  print '\n'

In [5]:
detect(image)

Detection started!
input fig: 
[[1 1 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 1 1]
 [1 1 1 1 0 0 1 1 0]
 [0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 1 1 1]]


first layer final output: 
[[1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]]


final detection: 
[[1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]]




Here the example shows a 9x9 image in which there are two fixed patterns in the image. One fixed pattern in the up-left corner and the another one is in the bottom-right corner. The link (https://ibb.co/k3phF7) shows the demo of how the fixed pattern activate the final output. The final output is one if and only if the 4x4 input pattern matches the fixed one. 

In [6]:
detect(image_large)
  

Detection started!
input fig: 
[[1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 1 1 1 1 0 0]
 [1 1 1 1 0 0 1 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 1 1 0 1 0 0 0]
 [0 0 0 0 0 1 0 1 1 1 0 0 0]
 [0 1 1 1 1 1 0 0 0 0 0 0 0]
 [0 1 0 0 1 1 1 1 1 1 1 1 0]]


first layer final output: 
[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


final detection: 
[[1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0

Here, I showed that the pattern detector can be applied to larger dimension images. 